#!/usr/bin/env bash
# Parses Apache log files in list format.
# Displays the number of occurrences, IP, and HTTP status
# Ordered from the greatest to the lowest number of occurrences

awk -F' ' '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -nr
