#!/usr/bin/env bash
# Displays "Best School" 10 times using a while loop.
# On the 9th iteration, displays "Hi" after "Best School".
j=1
while [ "$j" -le 10 ]
do
	if [ "$j" -eq 9 ]
	then
		echo "Best School"
		echo "Hi"
	else
        	echo "Best School"
	fi
        j=$(( j + 1 ))
done
